### PR TITLE
Solved issue #152

### PR DESCRIPTION
**Pull request by gdkwxn**
[#152](https://github.com/fatipardo/PDBClean-0.0.2/issues/152)
Added documentation to all functions

### CODE REVIEW

**Review by fatipardo — CHANGES_REQUESTED** [review]
Hi! Could you add a line in the description of AlignSequences_v3 that mentions that this version checks if an alignment has already been provided, before running muscle, and in that case just reads the existing alignment?

**Comment by gdkwxn** [comment]
Hi, I added the additional line. Sorry for the delay, I've been busy :(

**Review by fatipardo — APPROVED** [review]
Looks good!

**Comment by fatipardo** [comment]
> Hi, I added the additional line. Sorry for the delay, I've been busy :(

No worries! Thank you for submitting the pull request!

**Pull request merged**
